// <auto-generated />
using HealthCatalyst.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthCatalyst.API.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthCatalyst.API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Person_Id")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Person_Id");

                    b.ToTable("Interest", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Person_Id = 1,
                            Value = "Sleeping"
                        },
                        new
                        {
                            Id = 2,
                            Person_Id = 2,
                            Value = "Eating"
                        },
                        new
                        {
                            Id = 3,
                            Person_Id = 2,
                            Value = "Running"
                        },
                        new
                        {
                            Id = 4,
                            Person_Id = 2,
                            Value = "Playing"
                        },
                        new
                        {
                            Id = 5,
                            Person_Id = 3,
                            Value = "KPop"
                        },
                        new
                        {
                            Id = 6,
                            Person_Id = 3,
                            Value = "Reading"
                        },
                        new
                        {
                            Id = 7,
                            Person_Id = 4,
                            Value = "Reading"
                        });
                });

            modelBuilder.Entity("HealthCatalyst.API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("People", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "127 Elm Street",
                            Age = 9,
                            FirstName = "Jack",
                            LastName = "Cat"
                        },
                        new
                        {
                            Id = 2,
                            Address = "124 Rocky Brook Road",
                            Age = 8,
                            FirstName = "Jamie",
                            LastName = "Prugh"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 Elm Court",
                            Age = 32,
                            FirstName = "Marie",
                            LastName = "Collins"
                        },
                        new
                        {
                            Id = 4,
                            Address = "5 Elm Court",
                            Age = 87,
                            FirstName = "Geoff",
                            LastName = "Jack"
                        });
                });

            modelBuilder.Entity("HealthCatalyst.API.Models.Interest", b =>
                {
                    b.HasOne("HealthCatalyst.API.Models.Person", "Person")
                        .WithMany("Interests")
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HealthCatalyst.API.Models.Person", b =>
                {
                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
